# .github/workflows/ci.yml
name: ci

on: [push, pull_request]

jobs:
  test:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/ci.yml@main
    with:
      disable_phpcpd: true
      extra_plugin_runners: 'moodle-plugin-ci add-plugin catalyst/moodle-tool_mfa'

